package com.bibek.chatapplication.utils

const val NAME_KEY = "NAME_KEY"
const val GENDER_KEY = "GENDER_KEY"
const val PREFER_GENDER_KEY = "PREFER_GENDER_KEY"
const val CHAT_MESSAGE_DATABASE = "CHAT_MESSAGE_DATABASE"
const val BASE_URL = "https://dev.wefaaq.net/"
const val DATE_FORMAT_PATTERN = "yyyy-MM-dd HH:mm:ss.SSS"
const val KTOR_CLIENT = "Ktor Client"
const val GENERIC_ERROR_MESSAGE = "Something went wrong"
const val CONNECTION_TIMEOUT_MESSAGE = "Connection Timeout"
const val SOCKET_TIMEOUT_MESSAGE = "Socket Timeout"
const val UNKNOWN_IO_ERROR_MESSAGE = "Unknown IO Error"
const val UNKNOWN_ERROR_MESSAGE = "Unknown Error"
const val ERROR_DESCRIPTION_KEY = "error_description"
const val MESSAGE_KEY = "message"
const val STATUS_DESC_KEY = "statusDesc"
const val PREFERENCES_NAME = "Chat_Application"
const val UDID_NAME = "UDID_NAME"
const val PASSWORD_KEY = "PASSWORD"
const val ACCESS_TOKEN = "ACCESS_TOKEN"
const val USER_AGENT = "User-Agent"
const val CONTENT_TYPE = "Content-Type"
const val X_SESSION_ID = "X-Session-ID"
const val AUTHORIZATION = "Authorization"
const val DEVICE_ID = "DEVICE_ID"
const val TOKEN = "TOKEN"



